version: "3.8"

services:
  nginx-server:
    container_name: nginx-server
    image: "267157074835.dkr.ecr.ap-southeast-1.amazonaws.com/ready2go-order:0.7"
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile

  new-relic:
    image: "267157074835.dkr.ecr.ap-southeast-1.amazonaws.com/new-relic:0.1"
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
