version: "3.8"

services:
  nginx-server:
    build:
      context: client
    ports:
      - "8080:80"

  new-relic:
    build:
      context: new-relic
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
