name: Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure docker build works
        run: |
          docker build -t is458-web ./client
          docker build -t is458-relic ./new-relic

      - name: Create deployment package
        run: zip -r deploy.zip *

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Ready2GoWeb
          environment_name: Ready2GoWeb
          version_label: ${{ github.sha }}
          region: ap-southeast-1
          deployment_package: deploy.zip
