name: Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_WEB_REPOSITORY: ${{ secrets.WEB_REPO_NAME }}
          ECR_NEW_RELIC_REPOSITORY: ${{ secrets.NEW_RELIC_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f client/Dockerfile -t $ECR_REGISTRY/$ECR_WEB_REPOSITORY:$IMAGE_TAG .
          docker build -f client/new-relic/Dockerfile -t $ECR_REGISTRY/$ECR_NEW_RELIC_REPOSITORY:$IMAGE_TAG .

          docker push $ECR_REGISTRY/$ECR_WEB_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_NEW_RELIC_REPOSITORY:$IMAGE_TAG
